import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { Toaster } from "@/components/ui/sonner"
import "./globals.css"
import { AppSidebar } from "@/components/app-sidebar"
import LoginForm from "@/components/LoginForm"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "AskAi Chat with your PDF",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <div className="flex h-screen w-screen overflow-hidden">
            {/* Sidebar */}
            <AppSidebar />

            {/* Main Content */}
            <div className="flex flex-col flex-1 min-w-0">
              <header className="p-2 border-b flex items-center justify-between">
                <SidebarTrigger className="cursor-pointer" />
                <LoginForm />
              </header>

              <main className="flex-1 overflow-auto bg-background">
                {children}
              </main>

            </div>
          </div>
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  )
}






